# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.104.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "pre-build"
  lane :prebuild do
    increment_build_number(build_number: number_of_commits)
  end

  desc "Submit a new Beta Build to Apple HockeyApp"
  desc "This will also make sure the profile is up to date"
  
  lane :register do
    register_devices(devices_file: "./fastlane/devices.txt")
    match(type: "adhoc", force: "true")
    match(type: "development", force: "true")
  end

  desc "Build only"
  lane :build do
    match(type: "adhoc",
      readonly: true) 
    # more information: https://codesigning.guide

    gym(scheme: "loop",
      workspace: "loop.xcworkspace",
      include_bitcode: false,
      output_directory: "./build")
  end

  desc "Deploy a new version to hockey"
  lane :adhoc do
    match(type: "adhoc",
      readonly: true) 
    # more information: https://codesigning.guide

    gym(scheme: "loop",
      workspace: "loop.xcworkspace",
      include_bitcode: false,
      output_directory: "./build")

    hockey(
      api_token: "11c6ca25a67346e2a1f9167ae8ca6a65",
      public_identifier: "573abf65fdcb481b8fc932806b420fec",
      notify: '0',
      status: '2',
      notes: last_git_commit[:message] + "\n(Uploaded automatically via fastlane)"
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "loop") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer